name: Fetch checkout and run on NCI
on:
  pull_request:

jobs:
  setup-and-test:
    permissions:
      contents: "read"
      id-token: "write"
    timeout-minutes: 8640
    runs-on: self-hosted
    steps:
      - name: Set up hpci
        uses: Garvan-Data-Science-Platform/hpci-reusable-actions/.github/actions/setup-hpci@main
        with:
          submodule_token: ${{ secrets.SUBMODULE_TOKEN }}
          project_id: ${{ secrets.PROJECT_ID }}
          project_number: ${{ secrets.PROJECT_NUMBER }}
          registry_sa: ${{ secrets.REGISTRY_SA }}
          key_prefix: "prod_bio"
          hpci_version: "0.0.3"

      - name: Set env
        shell: bash
        run: |
          TIMESTAMP=$(date '+%Y%m%d_%H%M%S')
          REPO=${{ github.event.repository.name }}
          GIT_REF=${{ github.head_ref }}
          URL=git@github.com:${{ github.repository }}.git

          # Append each to $GITHUB_ENV
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
          echo "REPO=$REPO" >> $GITHUB_ENV
          echo "GIT_REF=$GIT_REF" >> $GITHUB_ENV
          echo "URL=$URL" >> $GITHUB_ENV

          # Use variables directly to define INSTANCE_PARENT
          INSTANCE_PARENT="/scratch/np30/test_repositories/$REPO/$GIT_REF/$TIMESTAMP"
          echo "INSTANCE_PARENT=$INSTANCE_PARENT" >> $GITHUB_ENV

      - name: Clone repo
        id: run_jobs
        run: |
          jobs=("clone")
          for job in "${jobs[@]}"; do
            hpci-exe \
              --user ${{secrets.USER_NAME}} \
              --host ${{secrets.HOST_NAME}} \
              --port 22 \
              --publicKey access_key.pub \
              --privateKey access_key \
              schedule \
              --script hpci-scripts/$job.pbs \
              --logFile $job.log \
              -c INSTANCE_PARENT=$INSTANCE_PARENT,REPO=$REPO,GIT_REF=$GIT_REF,URL=$URL
          done

      - name: Run pipeline
        run: |
          hpci-exe \
            --user ${{secrets.USER_NAME}} \
            --host ${{secrets.HOST_NAME}} \
            --port 22 \
            --publicKey access_key.pub \
            --privateKey access_key \
            schedule \
            --script JointCaller.sh \
            --logFile $INSTANCE_PARENT/$REPO/.nextflow.log \
            -c INSTANCE_PARENT=$INSTANCE_PARENT,REPO=$REPO,GIT_REF=$GIT_REF,URL=$URL

      - name: Clean up
        run: rm access_key*
